<?php
    $form  = $this->form;
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">
    &times;</button><div>')
    ->setMessageCloseString('</div></div>');
    
    
    $this->formElementErrors()
         ->setMessageOpenFormat('<div class="alert alert-warning"><button type="button" class="close" data-dismiss="alert">x</button>')
         ->setMessageCloseString('</div>')
         ->render($form);
    
    
    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    $form->setAttribute('action', $this->url('login' , array('controller' => 'Auth' , 'action' => 'login')));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag($form);
    
    
    
?>

<style type="text/css">
    input, label{
        clear: both;
        display: block;
    }
</style>