<?php
    $form = $this->form;
    echo $this->flashMessenger()
         ->setMessageOpenFormat('<div%s>')
         ->setMessageSeparatorString('<p></p>')
         ->setMessageCloseString('<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button></div>')
         ->render('error' , array('alert alert-danger'));
    
    
    $form->setAttribute('action', $this->url('login' , array('controller' => 'auth' , 'action' => 'login')));
    
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    
?>

<style type="text/css">
    input, label{
        clear: both;
        display: block;
    }
</style>